// <auto-generated />
using System;
using DND_App.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DND_App.Web.Migrations
{
    [DbContext(typeof(DnDDbContext))]
    [Migration("20250110145059_Initial DnDDbContext")]
    partial class InitialDnDDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DND_App.Web.Models.Domain.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArmorClass")
                        .HasColumnType("int");

                    b.Property<int>("CharacterClassId")
                        .HasColumnType("int");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CharacterRaceId")
                        .HasColumnType("int");

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("int");

                    b.Property<bool>("Inspiration")
                        .HasColumnType("bit");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("PassiveWisdom")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProficiencyBonus")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Wisdom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterClassId");

                    b.HasIndex("CharacterRaceId");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("DND_App.Web.Models.Domain.CharacterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HitDie")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CharacterClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HitDie = 12,
                            Name = "Barbarian"
                        },
                        new
                        {
                            Id = 2,
                            HitDie = 8,
                            Name = "Bard"
                        },
                        new
                        {
                            Id = 3,
                            HitDie = 8,
                            Name = "Cleric"
                        },
                        new
                        {
                            Id = 4,
                            HitDie = 8,
                            Name = "Druid"
                        },
                        new
                        {
                            Id = 5,
                            HitDie = 10,
                            Name = "Fighter"
                        },
                        new
                        {
                            Id = 6,
                            HitDie = 8,
                            Name = "Monk"
                        },
                        new
                        {
                            Id = 7,
                            HitDie = 10,
                            Name = "Paladin"
                        },
                        new
                        {
                            Id = 8,
                            HitDie = 10,
                            Name = "Ranger"
                        },
                        new
                        {
                            Id = 9,
                            HitDie = 8,
                            Name = "Rogue"
                        },
                        new
                        {
                            Id = 10,
                            HitDie = 6,
                            Name = "Sorcerer"
                        },
                        new
                        {
                            Id = 11,
                            HitDie = 8,
                            Name = "Warlock"
                        },
                        new
                        {
                            Id = 12,
                            HitDie = 6,
                            Name = "Wizard"
                        });
                });

            modelBuilder.Entity("DND_App.Web.Models.Domain.CharacterRace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharismaBonus")
                        .HasColumnType("int");

                    b.Property<int>("ConstitutionBonus")
                        .HasColumnType("int");

                    b.Property<int>("DexterityBonus")
                        .HasColumnType("int");

                    b.Property<int>("IntelligenceBonus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StrengthBonus")
                        .HasColumnType("int");

                    b.Property<int>("WisdomBonus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CharacterRaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharismaBonus = 1,
                            ConstitutionBonus = 0,
                            DexterityBonus = 0,
                            IntelligenceBonus = 2,
                            Name = "Aasimar",
                            StrengthBonus = 0,
                            WisdomBonus = 0
                        },
                        new
                        {
                            Id = 2,
                            CharismaBonus = 1,
                            ConstitutionBonus = 0,
                            DexterityBonus = 0,
                            IntelligenceBonus = 0,
                            Name = "Dragonborn",
                            StrengthBonus = 2,
                            WisdomBonus = 0
                        },
                        new
                        {
                            Id = 3,
                            CharismaBonus = 0,
                            ConstitutionBonus = 2,
                            DexterityBonus = 0,
                            IntelligenceBonus = 0,
                            Name = "Dwarf",
                            StrengthBonus = 0,
                            WisdomBonus = 0
                        },
                        new
                        {
                            Id = 4,
                            CharismaBonus = 0,
                            ConstitutionBonus = 0,
                            DexterityBonus = 2,
                            IntelligenceBonus = 0,
                            Name = "Elf",
                            StrengthBonus = 0,
                            WisdomBonus = 0
                        },
                        new
                        {
                            Id = 5,
                            CharismaBonus = 0,
                            ConstitutionBonus = 0,
                            DexterityBonus = 0,
                            IntelligenceBonus = 0,
                            Name = "Firbolg",
                            StrengthBonus = 1,
                            WisdomBonus = 2
                        },
                        new
                        {
                            Id = 6,
                            CharismaBonus = 0,
                            ConstitutionBonus = 0,
                            DexterityBonus = 1,
                            IntelligenceBonus = 0,
                            Name = "Air Genasi",
                            StrengthBonus = 0,
                            WisdomBonus = 0
                        },
                        new
                        {
                            Id = 7,
                            CharismaBonus = 0,
                            ConstitutionBonus = 0,
                            DexterityBonus = 0,
                            IntelligenceBonus = 0,
                            Name = "Earth Genasi",
                            StrengthBonus = 1,
                            WisdomBonus = 0
                        },
                        new
                        {
                            Id = 8,
                            CharismaBonus = 0,
                            ConstitutionBonus = 0,
                            DexterityBonus = 1,
                            IntelligenceBonus = 0,
                            Name = "Fire Genasi",
                            StrengthBonus = 0,
                            WisdomBonus = 0
                        },
                        new
                        {
                            Id = 9,
                            CharismaBonus = 0,
                            ConstitutionBonus = 1,
                            DexterityBonus = 0,
                            IntelligenceBonus = 0,
                            Name = "Water Genasi",
                            StrengthBonus = 0,
                            WisdomBonus = 0
                        },
                        new
                        {
                            Id = 10,
                            CharismaBonus = 0,
                            ConstitutionBonus = 0,
                            DexterityBonus = 0,
                            IntelligenceBonus = 2,
                            Name = "Gnome",
                            StrengthBonus = 0,
                            WisdomBonus = 0
                        },
                        new
                        {
                            Id = 11,
                            CharismaBonus = 0,
                            ConstitutionBonus = 1,
                            DexterityBonus = 0,
                            IntelligenceBonus = 0,
                            Name = "Goliath",
                            StrengthBonus = 2,
                            WisdomBonus = 0
                        },
                        new
                        {
                            Id = 12,
                            CharismaBonus = 2,
                            ConstitutionBonus = 0,
                            DexterityBonus = 0,
                            IntelligenceBonus = 0,
                            Name = "Half-Elf",
                            StrengthBonus = 0,
                            WisdomBonus = 0
                        },
                        new
                        {
                            Id = 13,
                            CharismaBonus = 0,
                            ConstitutionBonus = 0,
                            DexterityBonus = 2,
                            IntelligenceBonus = 0,
                            Name = "Halfling",
                            StrengthBonus = 0,
                            WisdomBonus = 0
                        },
                        new
                        {
                            Id = 14,
                            CharismaBonus = 0,
                            ConstitutionBonus = 1,
                            DexterityBonus = 0,
                            IntelligenceBonus = 0,
                            Name = "Half-Orc",
                            StrengthBonus = 2,
                            WisdomBonus = 0
                        },
                        new
                        {
                            Id = 15,
                            CharismaBonus = 1,
                            ConstitutionBonus = 1,
                            DexterityBonus = 1,
                            IntelligenceBonus = 1,
                            Name = "Human",
                            StrengthBonus = 1,
                            WisdomBonus = 1
                        },
                        new
                        {
                            Id = 16,
                            CharismaBonus = 0,
                            ConstitutionBonus = 0,
                            DexterityBonus = 2,
                            IntelligenceBonus = 0,
                            Name = "Kenku",
                            StrengthBonus = 0,
                            WisdomBonus = 0
                        },
                        new
                        {
                            Id = 17,
                            CharismaBonus = 0,
                            ConstitutionBonus = 0,
                            DexterityBonus = 2,
                            IntelligenceBonus = 0,
                            Name = "Tabaxi",
                            StrengthBonus = 0,
                            WisdomBonus = 0
                        },
                        new
                        {
                            Id = 18,
                            CharismaBonus = 2,
                            ConstitutionBonus = 0,
                            DexterityBonus = 0,
                            IntelligenceBonus = 1,
                            Name = "Tiefling",
                            StrengthBonus = 0,
                            WisdomBonus = 0
                        },
                        new
                        {
                            Id = 19,
                            CharismaBonus = 0,
                            ConstitutionBonus = 1,
                            DexterityBonus = 0,
                            IntelligenceBonus = 0,
                            Name = "Tortle",
                            StrengthBonus = 2,
                            WisdomBonus = 0
                        },
                        new
                        {
                            Id = 20,
                            CharismaBonus = 2,
                            ConstitutionBonus = 0,
                            DexterityBonus = 0,
                            IntelligenceBonus = 1,
                            Name = "Yuan-Ti Pureblood",
                            StrengthBonus = 0,
                            WisdomBonus = 0
                        });
                });

            modelBuilder.Entity("DND_App.Web.Models.Domain.ClassAbility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterClassId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterClassId");

                    b.ToTable("ClassAbilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacterClassId = 1,
                            Name = "Rage"
                        },
                        new
                        {
                            Id = 2,
                            CharacterClassId = 1,
                            Name = "Unarmored Defense"
                        },
                        new
                        {
                            Id = 3,
                            CharacterClassId = 2,
                            Name = "Bardic Inspiration"
                        },
                        new
                        {
                            Id = 4,
                            CharacterClassId = 2,
                            Name = "Song of Rest"
                        },
                        new
                        {
                            Id = 5,
                            CharacterClassId = 3,
                            Name = "Turn Undead"
                        },
                        new
                        {
                            Id = 6,
                            CharacterClassId = 3,
                            Name = "Divine Intervention"
                        },
                        new
                        {
                            Id = 7,
                            CharacterClassId = 4,
                            Name = "Wild Shape"
                        },
                        new
                        {
                            Id = 8,
                            CharacterClassId = 4,
                            Name = "DruidicCircle"
                        },
                        new
                        {
                            Id = 9,
                            CharacterClassId = 5,
                            Name = "Second Wind"
                        },
                        new
                        {
                            Id = 10,
                            CharacterClassId = 5,
                            Name = "Action Surge"
                        },
                        new
                        {
                            Id = 11,
                            CharacterClassId = 6,
                            Name = "Martial Arts"
                        },
                        new
                        {
                            Id = 12,
                            CharacterClassId = 6,
                            Name = "Ki Points"
                        },
                        new
                        {
                            Id = 13,
                            CharacterClassId = 7,
                            Name = "Lay on Hands"
                        },
                        new
                        {
                            Id = 14,
                            CharacterClassId = 7,
                            Name = "Divine Smite"
                        },
                        new
                        {
                            Id = 15,
                            CharacterClassId = 8,
                            Name = "Favored Enemy"
                        },
                        new
                        {
                            Id = 16,
                            CharacterClassId = 8,
                            Name = "Natural Explorer"
                        },
                        new
                        {
                            Id = 17,
                            CharacterClassId = 9,
                            Name = "Sneak Attack"
                        },
                        new
                        {
                            Id = 18,
                            CharacterClassId = 9,
                            Name = "Cunning Action"
                        },
                        new
                        {
                            Id = 19,
                            CharacterClassId = 10,
                            Name = "Metamagic"
                        },
                        new
                        {
                            Id = 20,
                            CharacterClassId = 10,
                            Name = "Font of Magic"
                        },
                        new
                        {
                            Id = 21,
                            CharacterClassId = 11,
                            Name = "Eldritch Invocations"
                        },
                        new
                        {
                            Id = 22,
                            CharacterClassId = 11,
                            Name = "Pact Magic"
                        },
                        new
                        {
                            Id = 23,
                            CharacterClassId = 12,
                            Name = "Arcane Recovery"
                        },
                        new
                        {
                            Id = 24,
                            CharacterClassId = 12,
                            Name = "Spell Mastery"
                        });
                });

            modelBuilder.Entity("DND_App.Web.Models.Domain.ClassSavingThrow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterClassId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterClassId");

                    b.ToTable("ClassSavingThrows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacterClassId = 1,
                            Name = "Strength"
                        },
                        new
                        {
                            Id = 2,
                            CharacterClassId = 1,
                            Name = "Constitution"
                        },
                        new
                        {
                            Id = 3,
                            CharacterClassId = 2,
                            Name = "Dexterity"
                        },
                        new
                        {
                            Id = 4,
                            CharacterClassId = 2,
                            Name = "Charisma"
                        },
                        new
                        {
                            Id = 5,
                            CharacterClassId = 3,
                            Name = "Wisdom"
                        },
                        new
                        {
                            Id = 6,
                            CharacterClassId = 3,
                            Name = "Charisma"
                        },
                        new
                        {
                            Id = 7,
                            CharacterClassId = 4,
                            Name = "Intelligence"
                        },
                        new
                        {
                            Id = 8,
                            CharacterClassId = 4,
                            Name = "Wisdom"
                        },
                        new
                        {
                            Id = 9,
                            CharacterClassId = 5,
                            Name = "Strength"
                        },
                        new
                        {
                            Id = 10,
                            CharacterClassId = 5,
                            Name = "Constitution"
                        },
                        new
                        {
                            Id = 11,
                            CharacterClassId = 6,
                            Name = "Strength"
                        },
                        new
                        {
                            Id = 12,
                            CharacterClassId = 6,
                            Name = "Dexterity"
                        },
                        new
                        {
                            Id = 13,
                            CharacterClassId = 7,
                            Name = "Wisdom"
                        },
                        new
                        {
                            Id = 14,
                            CharacterClassId = 7,
                            Name = "Charisma"
                        },
                        new
                        {
                            Id = 15,
                            CharacterClassId = 8,
                            Name = "Strength"
                        },
                        new
                        {
                            Id = 16,
                            CharacterClassId = 8,
                            Name = "Dexterity"
                        },
                        new
                        {
                            Id = 17,
                            CharacterClassId = 9,
                            Name = "Dexterity"
                        },
                        new
                        {
                            Id = 18,
                            CharacterClassId = 9,
                            Name = "Intelligence"
                        },
                        new
                        {
                            Id = 19,
                            CharacterClassId = 10,
                            Name = "Constitution"
                        },
                        new
                        {
                            Id = 20,
                            CharacterClassId = 10,
                            Name = "Charisma"
                        },
                        new
                        {
                            Id = 21,
                            CharacterClassId = 11,
                            Name = "Wisdom"
                        },
                        new
                        {
                            Id = 22,
                            CharacterClassId = 11,
                            Name = "Charisma"
                        },
                        new
                        {
                            Id = 23,
                            CharacterClassId = 12,
                            Name = "Intelligence"
                        },
                        new
                        {
                            Id = 24,
                            CharacterClassId = 12,
                            Name = "Wisdom"
                        });
                });

            modelBuilder.Entity("DND_App.Web.Models.Domain.RaceAbility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterRaceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterRaceId");

                    b.ToTable("RaceAbility");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacterRaceId = 1,
                            Name = "DwarvenVision"
                        },
                        new
                        {
                            Id = 2,
                            CharacterRaceId = 1,
                            Name = "Healing Hands"
                        },
                        new
                        {
                            Id = 3,
                            CharacterRaceId = 2,
                            Name = "Breath Weapon"
                        },
                        new
                        {
                            Id = 4,
                            CharacterRaceId = 2,
                            Name = "Draconic Ancestry"
                        },
                        new
                        {
                            Id = 5,
                            CharacterRaceId = 3,
                            Name = "DwarvenVision"
                        },
                        new
                        {
                            Id = 6,
                            CharacterRaceId = 3,
                            Name = "Dwarven Resilience"
                        },
                        new
                        {
                            Id = 7,
                            CharacterRaceId = 4,
                            Name = "Keen Senses"
                        },
                        new
                        {
                            Id = 8,
                            CharacterRaceId = 4,
                            Name = "Fey Ancestry"
                        },
                        new
                        {
                            Id = 9,
                            CharacterRaceId = 5,
                            Name = "Firbolg Magic"
                        },
                        new
                        {
                            Id = 10,
                            CharacterRaceId = 5,
                            Name = "Hidden Step"
                        },
                        new
                        {
                            Id = 11,
                            CharacterRaceId = 6,
                            Name = "Unending Breath"
                        },
                        new
                        {
                            Id = 12,
                            CharacterRaceId = 6,
                            Name = "Mingle with the Wind"
                        },
                        new
                        {
                            Id = 13,
                            CharacterRaceId = 7,
                            Name = "Earth Walk"
                        },
                        new
                        {
                            Id = 14,
                            CharacterRaceId = 7,
                            Name = "Merge with Stone"
                        },
                        new
                        {
                            Id = 15,
                            CharacterRaceId = 8,
                            Name = "DwarvenVision"
                        },
                        new
                        {
                            Id = 16,
                            CharacterRaceId = 8,
                            Name = "Fire Resistance"
                        },
                        new
                        {
                            Id = 17,
                            CharacterRaceId = 9,
                            Name = "Acid Resistance"
                        },
                        new
                        {
                            Id = 18,
                            CharacterRaceId = 9,
                            Name = "ShellDefense"
                        },
                        new
                        {
                            Id = 19,
                            CharacterRaceId = 10,
                            Name = "Gnome Cunning"
                        },
                        new
                        {
                            Id = 20,
                            CharacterRaceId = 10,
                            Name = "DwarvenVision"
                        },
                        new
                        {
                            Id = 21,
                            CharacterRaceId = 11,
                            Name = "Mountain Born"
                        },
                        new
                        {
                            Id = 22,
                            CharacterRaceId = 11,
                            Name = "Powerful Build"
                        },
                        new
                        {
                            Id = 23,
                            CharacterRaceId = 12,
                            Name = "DwarvenVision"
                        },
                        new
                        {
                            Id = 24,
                            CharacterRaceId = 12,
                            Name = "Skill Versatility"
                        },
                        new
                        {
                            Id = 25,
                            CharacterRaceId = 13,
                            Name = "Lucky"
                        },
                        new
                        {
                            Id = 26,
                            CharacterRaceId = 13,
                            Name = "Brave"
                        },
                        new
                        {
                            Id = 27,
                            CharacterRaceId = 14,
                            Name = "Relentless Endurance"
                        },
                        new
                        {
                            Id = 28,
                            CharacterRaceId = 14,
                            Name = "Savage Attack"
                        },
                        new
                        {
                            Id = 29,
                            CharacterRaceId = 15,
                            Name = "Versatile Ability"
                        },
                        new
                        {
                            Id = 30,
                            CharacterRaceId = 16,
                            Name = "Mimicry"
                        },
                        new
                        {
                            Id = 31,
                            CharacterRaceId = 16,
                            Name = "Expert Forgery"
                        },
                        new
                        {
                            Id = 32,
                            CharacterRaceId = 17,
                            Name = "Cat’s Claws"
                        },
                        new
                        {
                            Id = 33,
                            CharacterRaceId = 17,
                            Name = "Feline Agility"
                        },
                        new
                        {
                            Id = 34,
                            CharacterRaceId = 18,
                            Name = "Infernal Legacy"
                        },
                        new
                        {
                            Id = 35,
                            CharacterRaceId = 18,
                            Name = "Hellish Resistance"
                        },
                        new
                        {
                            Id = 36,
                            CharacterRaceId = 19,
                            Name = "Natural Armor"
                        },
                        new
                        {
                            Id = 37,
                            CharacterRaceId = 19,
                            Name = "Hold Breath"
                        },
                        new
                        {
                            Id = 38,
                            CharacterRaceId = 20,
                            Name = "Magic Resistance"
                        },
                        new
                        {
                            Id = 39,
                            CharacterRaceId = 20,
                            Name = "Poison Immunity"
                        });
                });

            modelBuilder.Entity("DND_App.Web.Models.Domain.RaceToolProficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterRaceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterRaceId");

                    b.ToTable("RaceToolProficiency");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacterRaceId = 1,
                            Name = "Alchemist's Supplies"
                        },
                        new
                        {
                            Id = 2,
                            CharacterRaceId = 1,
                            Name = "Calligrapher's Supplies"
                        },
                        new
                        {
                            Id = 3,
                            CharacterRaceId = 1,
                            Name = "Herbalism Kit"
                        },
                        new
                        {
                            Id = 4,
                            CharacterRaceId = 1,
                            Name = "Musical Instrument"
                        },
                        new
                        {
                            Id = 5,
                            CharacterRaceId = 1,
                            Name = "Painter's Supplies"
                        },
                        new
                        {
                            Id = 6,
                            CharacterRaceId = 2,
                            Name = "Smith's Tools"
                        },
                        new
                        {
                            Id = 7,
                            CharacterRaceId = 2,
                            Name = "Brewer's Supplies"
                        },
                        new
                        {
                            Id = 8,
                            CharacterRaceId = 2,
                            Name = "Calligrapher's Supplies"
                        },
                        new
                        {
                            Id = 9,
                            CharacterRaceId = 2,
                            Name = "Mason's Tools"
                        },
                        new
                        {
                            Id = 10,
                            CharacterRaceId = 2,
                            Name = "Dragonchess Set"
                        },
                        new
                        {
                            Id = 11,
                            CharacterRaceId = 3,
                            Name = "Smith's Tools"
                        },
                        new
                        {
                            Id = 13,
                            CharacterRaceId = 3,
                            Name = "Brewer's Supplies"
                        },
                        new
                        {
                            Id = 14,
                            CharacterRaceId = 3,
                            Name = "Mason's Tools"
                        },
                        new
                        {
                            Id = 15,
                            CharacterRaceId = 4,
                            Name = "Herbalism Kit"
                        },
                        new
                        {
                            Id = 16,
                            CharacterRaceId = 4,
                            Name = "Calligrapher's Supplies"
                        },
                        new
                        {
                            Id = 17,
                            CharacterRaceId = 4,
                            Name = "Musical Instrument"
                        },
                        new
                        {
                            Id = 18,
                            CharacterRaceId = 4,
                            Name = "Painter's Supplies"
                        },
                        new
                        {
                            Id = 19,
                            CharacterRaceId = 4,
                            Name = "Alchemist's Supplies"
                        },
                        new
                        {
                            Id = 20,
                            CharacterRaceId = 5,
                            Name = "Herbalism Kit"
                        },
                        new
                        {
                            Id = 21,
                            CharacterRaceId = 5,
                            Name = "Carpenter's Tools"
                        },
                        new
                        {
                            Id = 22,
                            CharacterRaceId = 5,
                            Name = "Cook's Utensils"
                        },
                        new
                        {
                            Id = 23,
                            CharacterRaceId = 5,
                            Name = "Mason's Tools"
                        },
                        new
                        {
                            Id = 24,
                            CharacterRaceId = 5,
                            Name = "Painter's Supplies"
                        },
                        new
                        {
                            Id = 25,
                            CharacterRaceId = 6,
                            Name = "Navigator's Tools"
                        },
                        new
                        {
                            Id = 26,
                            CharacterRaceId = 6,
                            Name = "Cartographer's Tools"
                        },
                        new
                        {
                            Id = 27,
                            CharacterRaceId = 6,
                            Name = "Tinker's Tools"
                        },
                        new
                        {
                            Id = 28,
                            CharacterRaceId = 6,
                            Name = "Flute"
                        },
                        new
                        {
                            Id = 29,
                            CharacterRaceId = 6,
                            Name = "Calligrapher's Supplies"
                        },
                        new
                        {
                            Id = 30,
                            CharacterRaceId = 7,
                            Name = "Smith's Tools"
                        },
                        new
                        {
                            Id = 31,
                            CharacterRaceId = 7,
                            Name = "Mason's Tools"
                        },
                        new
                        {
                            Id = 32,
                            CharacterRaceId = 7,
                            Name = "Miner's Tools"
                        },
                        new
                        {
                            Id = 33,
                            CharacterRaceId = 7,
                            Name = "Potter's Tools"
                        },
                        new
                        {
                            Id = 34,
                            CharacterRaceId = 7,
                            Name = "Cartographer's Tools"
                        },
                        new
                        {
                            Id = 35,
                            CharacterRaceId = 8,
                            Name = "Alchemist's Supplies"
                        },
                        new
                        {
                            Id = 36,
                            CharacterRaceId = 8,
                            Name = "Glassblower's Tools"
                        },
                        new
                        {
                            Id = 37,
                            CharacterRaceId = 8,
                            Name = "Smith's Tools"
                        },
                        new
                        {
                            Id = 38,
                            CharacterRaceId = 8,
                            Name = "Cook's Utensils"
                        },
                        new
                        {
                            Id = 39,
                            CharacterRaceId = 8,
                            Name = "Brewer's Supplies"
                        },
                        new
                        {
                            Id = 40,
                            CharacterRaceId = 9,
                            Name = "Navigator's Tools"
                        },
                        new
                        {
                            Id = 41,
                            CharacterRaceId = 9,
                            Name = "Fishing Tackle"
                        },
                        new
                        {
                            Id = 42,
                            CharacterRaceId = 9,
                            Name = "Cartographer's Tools"
                        },
                        new
                        {
                            Id = 43,
                            CharacterRaceId = 9,
                            Name = "Cook's Utensils"
                        },
                        new
                        {
                            Id = 44,
                            CharacterRaceId = 9,
                            Name = "Brewer's Supplies"
                        },
                        new
                        {
                            Id = 45,
                            CharacterRaceId = 10,
                            Name = "Tinker's Tools"
                        },
                        new
                        {
                            Id = 46,
                            CharacterRaceId = 10,
                            Name = "Alchemist's Supplies"
                        },
                        new
                        {
                            Id = 47,
                            CharacterRaceId = 10,
                            Name = "Artisan's Tools"
                        },
                        new
                        {
                            Id = 48,
                            CharacterRaceId = 10,
                            Name = "Cartographer's Tools"
                        },
                        new
                        {
                            Id = 49,
                            CharacterRaceId = 10,
                            Name = "Painter's Supplies"
                        },
                        new
                        {
                            Id = 50,
                            CharacterRaceId = 11,
                            Name = "Smith's Tools"
                        },
                        new
                        {
                            Id = 51,
                            CharacterRaceId = 11,
                            Name = "Mason's Tools"
                        },
                        new
                        {
                            Id = 52,
                            CharacterRaceId = 11,
                            Name = "Carpenter's Tools"
                        },
                        new
                        {
                            Id = 53,
                            CharacterRaceId = 11,
                            Name = "Cook's Utensils"
                        },
                        new
                        {
                            Id = 54,
                            CharacterRaceId = 11,
                            Name = "Brewer's Supplies"
                        },
                        new
                        {
                            Id = 55,
                            CharacterRaceId = 12,
                            Name = "Fiddle"
                        },
                        new
                        {
                            Id = 56,
                            CharacterRaceId = 12,
                            Name = "Calligrapher's Supplies"
                        },
                        new
                        {
                            Id = 57,
                            CharacterRaceId = 12,
                            Name = "Painter's Supplies"
                        },
                        new
                        {
                            Id = 58,
                            CharacterRaceId = 12,
                            Name = "Alchemist's Supplies"
                        },
                        new
                        {
                            Id = 59,
                            CharacterRaceId = 12,
                            Name = "Jeweler's Tools"
                        },
                        new
                        {
                            Id = 60,
                            CharacterRaceId = 13,
                            Name = "Cook's Utensils"
                        },
                        new
                        {
                            Id = 61,
                            CharacterRaceId = 13,
                            Name = "Brewer's Supplies"
                        },
                        new
                        {
                            Id = 62,
                            CharacterRaceId = 13,
                            Name = "Weaver's Tools"
                        },
                        new
                        {
                            Id = 63,
                            CharacterRaceId = 13,
                            Name = "Woodcarver's Tools"
                        },
                        new
                        {
                            Id = 64,
                            CharacterRaceId = 13,
                            Name = "Herbalism Kit"
                        },
                        new
                        {
                            Id = 65,
                            CharacterRaceId = 14,
                            Name = "Smith's Tools"
                        },
                        new
                        {
                            Id = 66,
                            CharacterRaceId = 14,
                            Name = "Leatherworker's Tools"
                        },
                        new
                        {
                            Id = 67,
                            CharacterRaceId = 14,
                            Name = "Carpenter's Tools"
                        },
                        new
                        {
                            Id = 68,
                            CharacterRaceId = 14,
                            Name = "Cook's Utensils"
                        },
                        new
                        {
                            Id = 69,
                            CharacterRaceId = 14,
                            Name = "Brewer's Supplies"
                        },
                        new
                        {
                            Id = 70,
                            CharacterRaceId = 15,
                            Name = "Smith's Tools"
                        },
                        new
                        {
                            Id = 71,
                            CharacterRaceId = 15,
                            Name = "Farmer's Tools"
                        },
                        new
                        {
                            Id = 72,
                            CharacterRaceId = 15,
                            Name = "Mason's Tools"
                        },
                        new
                        {
                            Id = 73,
                            CharacterRaceId = 15,
                            Name = "Brewer's Supplies"
                        },
                        new
                        {
                            Id = 74,
                            CharacterRaceId = 15,
                            Name = "Herbalism Kit"
                        },
                        new
                        {
                            Id = 75,
                            CharacterRaceId = 16,
                            Name = "Calligrapher's Supplies"
                        },
                        new
                        {
                            Id = 76,
                            CharacterRaceId = 16,
                            Name = "Disguise Kit"
                        },
                        new
                        {
                            Id = 77,
                            CharacterRaceId = 16,
                            Name = "Tinker's Tools"
                        },
                        new
                        {
                            Id = 78,
                            CharacterRaceId = 16,
                            Name = "Thieves' Tools"
                        },
                        new
                        {
                            Id = 79,
                            CharacterRaceId = 16,
                            Name = "Painter's Supplies"
                        },
                        new
                        {
                            Id = 80,
                            CharacterRaceId = 17,
                            Name = "Cartographer's Tools"
                        },
                        new
                        {
                            Id = 81,
                            CharacterRaceId = 17,
                            Name = "Calligrapher's Supplies"
                        },
                        new
                        {
                            Id = 82,
                            CharacterRaceId = 17,
                            Name = "Painter's Supplies"
                        },
                        new
                        {
                            Id = 83,
                            CharacterRaceId = 17,
                            Name = "Drums"
                        },
                        new
                        {
                            Id = 84,
                            CharacterRaceId = 17,
                            Name = "Thieves' Tools"
                        },
                        new
                        {
                            Id = 85,
                            CharacterRaceId = 18,
                            Name = "Alchemist's Supplies"
                        },
                        new
                        {
                            Id = 86,
                            CharacterRaceId = 18,
                            Name = "Calligrapher's Supplies"
                        },
                        new
                        {
                            Id = 87,
                            CharacterRaceId = 18,
                            Name = "Disguise Kit"
                        },
                        new
                        {
                            Id = 88,
                            CharacterRaceId = 18,
                            Name = "Lyre"
                        },
                        new
                        {
                            Id = 89,
                            CharacterRaceId = 18,
                            Name = "Forgery Kit"
                        },
                        new
                        {
                            Id = 90,
                            CharacterRaceId = 19,
                            Name = "Mason's Tools"
                        },
                        new
                        {
                            Id = 91,
                            CharacterRaceId = 19,
                            Name = "Carpenter's Tools"
                        },
                        new
                        {
                            Id = 92,
                            CharacterRaceId = 19,
                            Name = "Cook's Utensils"
                        },
                        new
                        {
                            Id = 93,
                            CharacterRaceId = 19,
                            Name = "Fishing Tackle"
                        },
                        new
                        {
                            Id = 94,
                            CharacterRaceId = 19,
                            Name = "Herbalism Kit"
                        },
                        new
                        {
                            Id = 95,
                            CharacterRaceId = 20,
                            Name = "Poisoner's Kit"
                        },
                        new
                        {
                            Id = 96,
                            CharacterRaceId = 20,
                            Name = "Alchemist's Supplies"
                        },
                        new
                        {
                            Id = 97,
                            CharacterRaceId = 20,
                            Name = "Disguise Kit"
                        },
                        new
                        {
                            Id = 98,
                            CharacterRaceId = 20,
                            Name = "Forgery Kit"
                        },
                        new
                        {
                            Id = 99,
                            CharacterRaceId = 20,
                            Name = "Calligrapher's Supplies"
                        });
                });

            modelBuilder.Entity("DND_App.Web.Models.Domain.RaceWeaponProficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterRaceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterRaceId");

                    b.ToTable("RaceWeaponProficiency");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacterRaceId = 1,
                            Name = "None"
                        },
                        new
                        {
                            Id = 2,
                            CharacterRaceId = 2,
                            Name = "None"
                        },
                        new
                        {
                            Id = 3,
                            CharacterRaceId = 3,
                            Name = "Battleaxe"
                        },
                        new
                        {
                            Id = 4,
                            CharacterRaceId = 3,
                            Name = "Handaxe"
                        },
                        new
                        {
                            Id = 5,
                            CharacterRaceId = 3,
                            Name = "Throwing Hammer"
                        },
                        new
                        {
                            Id = 6,
                            CharacterRaceId = 3,
                            Name = "Warhammer"
                        },
                        new
                        {
                            Id = 7,
                            CharacterRaceId = 4,
                            Name = "Longsword"
                        },
                        new
                        {
                            Id = 8,
                            CharacterRaceId = 4,
                            Name = "Shortsword"
                        },
                        new
                        {
                            Id = 9,
                            CharacterRaceId = 4,
                            Name = "Shortbow"
                        },
                        new
                        {
                            Id = 10,
                            CharacterRaceId = 4,
                            Name = "Longbow"
                        },
                        new
                        {
                            Id = 11,
                            CharacterRaceId = 5,
                            Name = "None"
                        },
                        new
                        {
                            Id = 12,
                            CharacterRaceId = 6,
                            Name = "None"
                        },
                        new
                        {
                            Id = 13,
                            CharacterRaceId = 7,
                            Name = "None"
                        },
                        new
                        {
                            Id = 14,
                            CharacterRaceId = 8,
                            Name = "None"
                        },
                        new
                        {
                            Id = 15,
                            CharacterRaceId = 9,
                            Name = "None"
                        },
                        new
                        {
                            Id = 16,
                            CharacterRaceId = 10,
                            Name = "None"
                        },
                        new
                        {
                            Id = 17,
                            CharacterRaceId = 11,
                            Name = "None"
                        },
                        new
                        {
                            Id = 18,
                            CharacterRaceId = 12,
                            Name = "Longsword"
                        },
                        new
                        {
                            Id = 19,
                            CharacterRaceId = 12,
                            Name = "Shortsword"
                        },
                        new
                        {
                            Id = 20,
                            CharacterRaceId = 12,
                            Name = "Shortbow"
                        },
                        new
                        {
                            Id = 21,
                            CharacterRaceId = 12,
                            Name = "Longbow"
                        },
                        new
                        {
                            Id = 22,
                            CharacterRaceId = 13,
                            Name = "None"
                        },
                        new
                        {
                            Id = 23,
                            CharacterRaceId = 14,
                            Name = "None"
                        },
                        new
                        {
                            Id = 24,
                            CharacterRaceId = 15,
                            Name = "Longsword"
                        },
                        new
                        {
                            Id = 25,
                            CharacterRaceId = 15,
                            Name = "Shortsword"
                        },
                        new
                        {
                            Id = 26,
                            CharacterRaceId = 16,
                            Name = "None"
                        },
                        new
                        {
                            Id = 27,
                            CharacterRaceId = 17,
                            Name = "None"
                        },
                        new
                        {
                            Id = 28,
                            CharacterRaceId = 18,
                            Name = "None"
                        },
                        new
                        {
                            Id = 29,
                            CharacterRaceId = 19,
                            Name = "None"
                        },
                        new
                        {
                            Id = 30,
                            CharacterRaceId = 20,
                            Name = "None"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityUser<Guid>");
                });

            modelBuilder.Entity("DND_App.Web.Models.Domain.Character", b =>
                {
                    b.HasOne("DND_App.Web.Models.Domain.CharacterClass", "CharacterClass")
                        .WithMany()
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DND_App.Web.Models.Domain.CharacterRace", "CharacterRace")
                        .WithMany()
                        .HasForeignKey("CharacterRaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterClass");

                    b.Navigation("CharacterRace");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DND_App.Web.Models.Domain.ClassAbility", b =>
                {
                    b.HasOne("DND_App.Web.Models.Domain.CharacterClass", "CharacterClass")
                        .WithMany("ClassAbilities")
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterClass");
                });

            modelBuilder.Entity("DND_App.Web.Models.Domain.ClassSavingThrow", b =>
                {
                    b.HasOne("DND_App.Web.Models.Domain.CharacterClass", "CharacterClass")
                        .WithMany("ClassSavingThrows")
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterClass");
                });

            modelBuilder.Entity("DND_App.Web.Models.Domain.RaceAbility", b =>
                {
                    b.HasOne("DND_App.Web.Models.Domain.CharacterRace", "CharacterRace")
                        .WithMany("RaceAbilities")
                        .HasForeignKey("CharacterRaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterRace");
                });

            modelBuilder.Entity("DND_App.Web.Models.Domain.RaceToolProficiency", b =>
                {
                    b.HasOne("DND_App.Web.Models.Domain.CharacterRace", "CharacterRace")
                        .WithMany("RaceToolProficiencies")
                        .HasForeignKey("CharacterRaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterRace");
                });

            modelBuilder.Entity("DND_App.Web.Models.Domain.RaceWeaponProficiency", b =>
                {
                    b.HasOne("DND_App.Web.Models.Domain.CharacterRace", "CharacterRace")
                        .WithMany("RaceWeaponProficiencies")
                        .HasForeignKey("CharacterRaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterRace");
                });

            modelBuilder.Entity("DND_App.Web.Models.Domain.CharacterClass", b =>
                {
                    b.Navigation("ClassAbilities");

                    b.Navigation("ClassSavingThrows");
                });

            modelBuilder.Entity("DND_App.Web.Models.Domain.CharacterRace", b =>
                {
                    b.Navigation("RaceAbilities");

                    b.Navigation("RaceToolProficiencies");

                    b.Navigation("RaceWeaponProficiencies");
                });
#pragma warning restore 612, 618
        }
    }
}
